# Generated by Django 2.1.1 on 2018-09-20 22:10

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TravelCache',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_point', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='TravelTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('travel_time_minutes', models.FloatField()),
                ('osm_id', models.PositiveIntegerField()),
                ('start_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.TravelCache')),
            ],
        ),
    ]
