# Generated by Django 2.1.1 on 2018-09-30 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='quality',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
