# Generated by Django 2.1.1 on 2018-09-12 22:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("api", "0001_initial")]

    operations = [
        migrations.AlterField(
            model_name="trailhead",
            name="node",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="api.Node", unique=True
            ),
        )
    ]
