# Generated by Django 2.1.1 on 2018-09-12 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("api", "0002_auto_20180912_2222")]

    operations = [
        migrations.AddField(
            model_name="trailnetwork",
            name="unique_id",
            field=models.CharField(default="", max_length=100, unique=True),
            preserve_default=False,
        )
    ]
