# Generated by Django 2.1.1 on 2018-09-12 22:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_trailnetwork_unique_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trailhead',
            name='node',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.Node'),
        ),
    ]
