# Generated by Django 2.1.1 on 2018-09-13 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_trailhead_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='node',
            old_name='lon',
            new_name='lng',
        ),
    ]
