version: '3'
services:
  db:
    #ports:
    #- "5432:5432"
    image: mdillon/postgis
    env_file:
    - local.env
    volumes:
    - trails-db:/var/lib/postgresql/data
  app:
    ports:
    - "8080:8000"
    cap_add:
    - SYS_PTRACE
    volumes:
    - ./trails:/app
    - ../trails-data/:/trail-data/
    env_file:
    - local.env
    build:
      dockerfile: Dockerfile.dev
      context: .
    command: ["sleep", "infinity"]
    links:
    - db
    - redis
  worker:
    build:
      dockerfile: Dockerfile.dev
      context: .
    env_file:
      - local.env
    volumes:
      - ./trails:/app
      - ../trails-data/:/trail-data/
    depends_on:
      - db
      - redis

    command: celery -A trails worker -l info
  redis:
    image: redis:latest
volumes:
  trails-db:

