FROM python:3.7
WORKDIR /app/
# pyosmium dependencies
RUN apt-get update 
RUN apt-get install -y build-essential libboost-python-dev \
                     libexpat1-dev zlib1g-dev libbz2-dev \
                     default-jdk
RUN apt-get install -y gdal-bin libsqlite3-mod-spatialite

RUN apt-get install -y htop vim
RUN apt-get install -y postgresql-client

RUN curl -O http://www.mkgmap.org.uk/download/splitter-r597.zip
RUN unzip splitter-r597.zip

RUN curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -
RUN echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list
RUN apt-get update && apt-get install -y yarn
COPY trails/package.json /app/package.json
COPY trails/yarn.lock /app/yarn.lock
RUN yarn install

RUN pip install pipenv
COPY trails/Pipfile /app/
COPY trails/Pipfile.lock /app/
RUN pipenv install --pre --system && rm -r ~/.cache
COPY trails/ /app/
EXPOSE 8000
RUN python manage.py check
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
