# Generated by Django 2.1.1 on 2020-06-18 20:23

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import django_measurement.models
import measurement.measures.distance
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Circuit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('route', django.contrib.gis.db.models.fields.LineStringField(dim=3, srid=4326)),
                ('total_length', django_measurement.models.MeasurementField(measurement=measurement.measures.distance.Distance)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('point', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326)),
                ('osm_id', models.BigIntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='TrailNetwork',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.TextField()),
                ('trails', django.contrib.gis.db.models.fields.MultiLineStringField(srid=4326)),
                ('bounding_box', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
                ('total_length', django_measurement.models.MeasurementField(measurement=measurement.measures.distance.Distance)),
                ('graph', models.BinaryField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='circuit',
            name='network',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='est.TrailNetwork'),
        ),
    ]
