# Generated by Django 2.1.1 on 2018-10-13 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_route_quality'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='name',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='route',
            name='elevation_gain',
            field=models.FloatField(db_index=True),
        ),
        migrations.AlterField(
            model_name='route',
            name='length_km',
            field=models.FloatField(db_index=True),
        ),
    ]
