# Generated by Django 2.1.1 on 2018-10-29 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("api", "0002_route_osm_rep")]

    operations = [
        migrations.AlterField(
            model_name="route",
            name="osm_rep",
            field=models.BinaryField(default=None, null=True),
        )
    ]
