# Generated by Django 2.1.1 on 2018-11-07 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20181029_0046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='osm_id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='traveltime',
            name='osm_id',
            field=models.BigIntegerField(),
        ),
    ]
