# Generated by Django 2.1.1 on 2018-11-07 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20181107_0343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trailhead',
            name='name',
            field=models.TextField(max_length=32),
        ),
    ]
