# Generated by Django 2.1.1 on 2018-11-09 17:39

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20181107_0602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='point',
            field=django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326),
        ),
    ]
