# Generated by Django 2.1.1 on 2018-11-11 18:37

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("api", "0006_auto_20181109_1739")]

    operations = [
        migrations.AlterField(
            model_name="route",
            name="nodes",
            field=django.contrib.gis.db.models.fields.LineStringField(dim=3, srid=4326),
        )
    ]
