apiVersion: apps/v1
kind: Deployment
metadata:
  name: trails-app
  labels:
    app: trails-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: trails-app
  template:
    metadata:
      labels:
        app: trails-app
    spec:
      containers:
      - name: trails-app
        image: gcr.io/trailfinder-1536773117692/trails-app
        resources:
          requests:
            cpu: 50m
        ports:
        - containerPort: 8000
        readinessProbe:
          httpGet:
            path: /api/statusz
            port: 8000
            scheme: HTTP
        livenessProbe:
          httpGet:
            path: /api/statusz
            port: 8000
            scheme: HTTP
        env:
        - name: SERVER
          value: trails-app
        - name: ENV
          value: 'prod'
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: cloudsql-db-credentials
              key: username
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: cloudsql-db-credentials
              key: password
        - name: DB_HOST
          value: 127.0.0.1
        - name: DB_PORT
          value: '5432'
        - name: POSTGRES_DB
          value: trails-db-green
      - name: cloudsql-proxy
        image: gcr.io/cloudsql-docker/gce-proxy:1.11
        command: ["/cloud_sql_proxy",
                  "-instances=trailfinder-1536773117692:us-west1:trails-db=tcp:5432",
                  "-credential_file=/secrets/cloudsql/credentials.json"]
        securityContext:
          runAsUser: 2  # non-root user
          allowPrivilegeEscalation: false
        volumeMounts:
          - name: cloudsql-instance-credentials
            mountPath: /secrets/cloudsql
            readOnly: true
      volumes:
      - name: cloudsql-instance-credentials
        secret:
          secretName: cloudsql-instance-credentials
---
apiVersion: v1
kind: Service
metadata:
  name: trails-app-service
  labels:
    app: trails-app
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 8000
    protocol: TCP
  selector:
    app: trails-app
