version: '3'
services:
  db:
    #ports:
    #- "5432:5432"
    image: mdillon/postgis
    env_file:
    - local.env
    volumes:
    - trails-db:/var/lib/postgresql/data
  app:
    ports:
    - "8080:8000"
    cap_add:
    - SYS_PTRACE
    volumes:
    - ./trails:/app
    - ../../trails-data/:/trail-data/
    build: .
    env_file:
    - local.env
    command: ["sleep", "infinity"]
    links:
    - db
volumes:
  trails-db:

