# Generated by Django 2.1.1 on 2020-06-20 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('est', '0002_auto_20200620_2108'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trailnetwork',
            old_name='bounding_box',
            new_name='poly',
        ),
    ]
