# Generated by Django 2.2.13 on 2020-07-02 22:09

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('est', '0003_auto_20200620_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trailnetwork',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='networks', to='est.Import'),
        ),
        migrations.CreateModel(
            name='CircuitAnalysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.IntegerField(choices=[(0, 'in_progress'), (1, 'complete'), (2, 'error')])),
                ('error', models.TextField(blank=True)),
                ('network', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='est.TrailNetwork')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
