# Generated by Django 2.2.13 on 2020-07-02 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('est', '0004_auto_20200702_2209'),
    ]

    operations = [
        migrations.AddField(
            model_name='circuit',
            name='error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='circuit',
            name='status',
            field=models.IntegerField(choices=[(0, 'not_started'), (1, 'in_progress'), (1, 'complete'), (2, 'error')], default=1),
        ),
        migrations.DeleteModel(
            name='CircuitAnalysis',
        ),
    ]
