# Generated by Django 2.2.13 on 2020-07-03 15:15

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('est', '0005_auto_20200702_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='circuit',
            name='route',
            field=django.contrib.gis.db.models.fields.LineStringField(dim=3, null=True, srid=4326),
        ),
    ]
