# Generated by Django 2.2.13 on 2020-07-03 15:19

from django.db import migrations
import django_measurement.models
import measurement.measures.distance


class Migration(migrations.Migration):

    dependencies = [
        ('est', '0006_auto_20200703_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='circuit',
            name='total_length',
            field=django_measurement.models.MeasurementField(measurement=measurement.measures.distance.Distance, null=True),
        ),
    ]
