# Generated by Django 2.2.13 on 2020-07-04 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('est', '0007_auto_20200703_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='circuit',
            name='status',
            field=models.IntegerField(choices=[(0, 'not_started'), (1, 'in_progress'), (2, 'complete'), (3, 'error')], default=2),
        ),
    ]
