# Generated by Django 2.2.13 on 2020-07-05 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('est', '0008_auto_20200704_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='import',
            name='name',
            field=models.TextField(blank=True),
        ),
    ]
