# Generated by Django 2.2.13 on 2020-07-06 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('est', '0010_trailnetwork_trailheads'),
    ]

    operations = [
        migrations.AddField(
            model_name='trailnetwork',
            name='digest',
            field=models.TextField(default=''),
        ),
    ]
