# Generated by Django 2.2.13 on 2020-07-06 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('est', '0011_trailnetwork_digest'),
    ]

    operations = [
        migrations.AddField(
            model_name='import',
            name='complete',
            field=models.BooleanField(default=True),
        ),
    ]
