# Generated by Django 2.2.13 on 2020-07-06 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('est', '0012_import_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='import',
            name='sha256_sum',
            field=models.TextField(default='old'),
        ),
    ]
