# Generated by Django 2.2.13 on 2020-07-06 21:38

from django.db import migrations, models


def set_area(apps, schema_editor):
    TrailNetwork = apps.get_model('est', 'TrailNetwork')
    for network in TrailNetwork.objects.all():
        network.area = network.poly.area
        network.save()


class Migration(migrations.Migration):
    dependencies = [
        ('est', '0013_import_sha256_sum'),
    ]

    operations = [
        migrations.AddField(
            model_name='trailnetwork',
            name='area',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.RunPython(set_area)
    ]
