# Generated by Django 2.2.13 on 2020-07-06 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('est', '0014_trailnetwork_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trailnetwork',
            name='area',
            field=models.FloatField(db_index=True),
        ),
    ]
